### ISSUE TITLE
Protocol 4.00 support for Direct and Server gateways

### ISSUE THREAD

**Issue by terryupton** [craftcms/commerce-sagepay#20] opened 2022-01-19 13:29 UTC
### Description
I just wondered if there was any update on the support and integration for Protocol 4.00?
I know that this plugin relies on the OmniPay repo and there are comments on there <https://github.com/thephpleague/omnipay-sagepay/issues/168>.

However, I am conscious this plugin is out of date and dates are getting close to requirement (14 March 2022) I believe? 

Does Craft intend to continue support for SagePay (Opayo) as a gateway?

**Comment by andrewhawkes** [comment] 2022-01-20 14:22
I've got a couple of sites relying on this plugin functioning too. I know the plugin heavily relies on Omnipay but is there anything that can be done to patch it until they update Omnipay?

**Comment by terryupton** [comment] 2022-02-08 11:17
Just following up on this again, as I know there has been some feedback on the Discord channel.
Just wondering if there was any further update or anything you can put out in the public to reassure us all in regards to the March deadline.

**Comment by andrewhawkes** [comment] 2022-02-10 18:14
Bump 
![](https://media.giphy.com/media/h6r8C9dTRhWXd83Gco/giphy-downsized-large.gif)

**Comment by rickmills** [comment] 2022-02-11 08:21
This likely needs @brandonkelly and @angrybrad tagged as they may not be aware of the impending crisis that will affect a big chunk of craft commerce customers.

**Comment by nfourtythree** [comment] 2022-02-11 08:27
Hi All,

Probably best to give an update here but some of you may already be aware of this. We are tracking the progress of the pending PRs on the omnipay library. We are also in conversation with the maintainer of that library to try and get things moving along and tested.

We have plans in place for all eventualities so that we will have a solution in place within a significant time before the deadline. This should give everyone enough time to get things sorted, updated and tested before that date passes.

Updates will be posted here as things progress, so please keep subscribed to this issue.

I understand the time pressure and importance of this, please keep all comments constructive and related to the issue.

Thanks!

**Comment by nfourtythree** [comment] 2022-02-11 09:47
Along with the previous message, we have now submitted our own PR to the package: thephpleague/omnipay-sagepay#173 which we have been working on for the last couple of days.

We have tested this with our test account for both the Server and Direct gateways and it appears everything seems to be in working order.

It would be great if anyone could test out this PR to see if everything works as expected in their projects locally and on a staging site. This would give us great feedback to get things pushed through or make any changes that might be required.

To test the PR you would need to add the following to your project's `composer.json` file and then run `composer update`:

```json
{
    "require": {
		...
        "omnipay/sagepay": "dev-master as 3.0"
    }
    "repositories": [
        {
            "url": "https://github.com/craftcms/omnipay-sagepay.git",
            "type": "git"
        }
    ]
}
```

Please let me know how you get on, thanks!

**Comment by nfourtythree** [comment] 2022-02-11 12:18
The PR has now been merged and the maintainers are looking for confirmation that the changes work as expected.

[I wrote some instructions](https://github.com/thephpleague/omnipay-sagepay/issues/168#issuecomment-1036154653) on how to get things up and running to test everything out. As it includes an update to this plugin.

**Comment by fantasticmachine** [comment] 2022-02-17 11:50
I've just installed this new update and I'm not convinced things are quite right.
I tried various test card numbers to simulate different 3DS conditions and they ALL passed and allowed the payment - which surprised me.
Then I found this SE post about testing 3DS2 workflow on SagePay/Opayo https://stackoverflow.com/questions/65329436/sagepay-3d-secure-v2-flow

That seems to indicate using different "passwords" on the SagePay/Opayo checkout screen to simulate different conditions.
Indeed, I tried "CHALLENGE" and was returned to my site with an error about 3DS2 being required - which kind of seems right. However the basket was emptied.

It looks like the user is being returned to my order summary page but has lost the reference to their cart. So while the cart is still there in Active Carts, the user is seeing a new, empty one when they are returned to the site.
Not sure if this is a "Me" issue or something with the gateway plugin.

**Comment by terryupton** [comment] 2022-02-28 10:23
@nfourtythree - I have tested a simple server integration today and everything seems to work as expected.
Are there any specific test cases you want us to trial? 

The only one thing I thought I should mention, is that when using one of the SagePay test cards that are supposed to 3D secure error, it seems to still process the transaction and return to the completed order screen.
This is when using a card that references `(E)` on the `3D Secure Response from Opayo` column.
So this might be a test environment/Opayo issue?

When using one of the passwords to force an error, then the error appears on the SagePay screen and you need to enter the card again as expected.

---- 

What is your timeline for getting this approved and rolled out as stable?

**Comment by terryupton** [comment] 2022-02-28 10:43
Further to the above comment. I tested the SagePay test cards that are supposed to 3D secure error on the old previous version of the plug-in (Protocol v3) and the same outcome occurred. So this is perhaps a non-issue.

**Comment by thisiscap** [comment] 2022-02-28 12:29
Made the update to a staging site today that uses a Direct integration and am having no issues with test orders. 

Seeing the same as others with all test cards being accepted without 3D Secure Response prompts, regardless of card numbers or any 'magic values'. After @terryupton's comment I tested on the previous plugin version as well and it's the same so perhaps that's a different SagePay/Opayo issue.

**Comment by fantasticmachine** [comment] 2022-02-28 17:33
@terryupton I think it's an issue with SagePay/Opayo not updating their documentation with regards to cards to test the different success/fail scenarios.

**Comment by terryupton** [comment] 2022-03-02 14:01
We have done some further testing on a more custom install that uses this as a base and builds on it for using SagePay Tokens and that site seems to also work as expected in terms of transactions and payments. As an aside - we have a slight issue in updating the tokens with the new SchemeTraceID, but we are working to sole this and I think this is not related to this plugin directly either.

**Comment by rickmills** [comment] 2022-03-02 14:45
Just to chime in we've started rolling this out to our live sites, and can confirm it's working as expected. Just waiting for a stable tag now :)

**Comment by andrewhawkes** [comment] 2022-03-03 18:03
@nfourtythree I've just tried this in test mode with the SagePay Server integration on a staging site and all appears to be working as expected. My modifications to the data such as adding the SKU to the description and adding VAT to items is also working as expected.

**Comment by andrewhawkes** [comment] 2022-03-03 18:30
I've just tried this in test mode with the SagePay Server integration on a staging site and all payments have gone through.
I've enabled the 3D secure option on the test SagePay account but regardless fo what cards I use from here: https://www.opayo.co.uk/support/getting-started/testing-your-account/process-a-test-transaction I cannot get it to prompt for a password?

Other than that everything seems to be going through as normal including my modifications for adding VAT and SKUs to line items.

**Comment by rickmills** [comment] 2022-03-04 12:59
I think thats an issue on SagePays end @andrewhawkes, if you manually set 'Apply3DSecure' to 1 (only for testing) it forces it to show. Bit of a pain, not sure why they recently disabled it as default.

**Comment by shetlandrew** [comment] 2022-03-07 17:00
@rickmills I tried setting 'Apply3DSecure' to 1 in AbstractGateway.php but I'm now getting a "ThreeDSNotificationURL field is required" validation error after entering one of the Opayo test cards that returns a 3D secure response. I tried the two different requires in composer.json ("omnipay/sagepay": "dev-master as 3.0" and "craftcms/commerce-sagepay": "dev-feature/protocol-4-compatibility as 4.0") with the same results. Is there some step I'm missing?

**Comment by rickmills** [comment] 2022-03-08 09:36
> @rickmills I tried setting 'Apply3DSecure' to 1 in AbstractGateway.php but I'm now getting a "ThreeDSNotificationURL field is required" validation error after entering one of the Opayo test cards that returns a 3D secure response. I tried the two different requires in composer.json ("omnipay/sagepay": "dev-master as 3.0" and "craftcms/commerce-sagepay": "dev-feature/protocol-4-compatibility as 4.0") with the same results. Is there some step I'm missing? I'm using the Sage Pay Direct gateway.

Think you'll need to @ one of the craft guys to help with that one, not sure why it'd be erroring over that

**Comment by terryupton** [comment] 2022-03-09 11:15
Hey @nfourtythree - any further update at all?
Conscious this is days away now....

**Comment by nfourtythree** [comment] 2022-03-09 20:40
Hi All

Version `4.0` of this plugin has now been released.

This version includes the update to the `4.00` API protocol.

Due to the nature of this update, we decided to make this a major version bump.

This means you will need to update your `craftcms/commerce-sagepay` requirement in `composer.json` to be:

```
	"craftcms/commerce-sagepay": "^4.0"
```

Then run `composer update`, this should get you all the latest files.

Please let us know if you encounter any issues.

Thank you for the time and effort everyone has put in to get this all updated.

Thanks!

**Closed by nfourtythree** 2022-03-09 20:40 UTC
Labels: bug

**Comment by peteralewis** [comment] 2022-03-15 13:31
Has anyone actually got this to work reliable on a production server? We're seeing more than 50% of the orders having issues. `"StatusDetail": "3333 : The ClientIPAddress is missing.",`

The problem is that SagePay doesn't support IPv6, and now requires an IP. The commerce-omnipay library this plugin uses doesn't accept an IP via the payment post data (whereas thephpleague/omnipay-sagepay does).

Instead the IP gets injected by commerce-omnipay directly from Craft, which could be IPv4 or IPv6 depending (I assume) on the device, browser or internet provider (?) of the user. And falls back to an empty string.
`'clientIp' => Craft::$app->getRequest()->userIP ?? '',`

I will post the issue on commerce-omnipay repo, but just wanted to know if anyone else is experiencing problems?
