### ISSUE TITLE
Saving card details with SagePay

### ISSUE THREAD

**Issue by terryupton** [craftcms/commerce-sagepay#13] opened 2021-02-19 16:55 UTC
### Description
Is there any way to stored payment cards for integration with SagePay (Opayo)?

Sagepay hint that this is a feature using tokens, but I cannot see this is an option or supported with Craft Commerce and Sagepay Gateway plugin.

https://www.opayo.co.uk/support/12/36/sage-pay-token-system-understanding-the-process
https://github.com/thephpleague/omnipay-sagepay

This has been requested by my client and would be amazing if this could be implemented.

**Comment by nfourtythree** [comment] 2021-06-18 09:07
Hi @terryupton 

This is a duplicate of #11 

Will close this in favour of the original issue/feature request.

Please make sure to put any information/feedback you may have in that issue.

Thanks!

**Closed by nfourtythree** 2021-06-18 09:07 UTC
Labels: enhancement
